name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # あなたのRailsアプリケーションのRubyバージョンに合わせてください
    - name: Install dependencies
      run: |
        yarn install
        bundle install
    - name: Build Docker image
      run: |
        docker build . --tag myapp:latest --build-arg RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
    - name: Precompile Rails assets
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: docker run -e RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} myapp:latest RAILS_ENV=production bundle exec rake assets:precompile